name: deploy model

on:
  workflow_run:
    workflows: [ "build model" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and tag docker image
        run: |
          docker build -t mahmoudalbardan/valveapp:latest .
          docker tag mahmoudalbardan/valveapp:latest mahmoudalbardan/valveapp:${{github.sha}}

      - name: push built image to docker hub
        run: |
          docker push mahmoudalbardan/valveapp:latest
          docker push mahmoudalbardan/valveapp:${{github.sha}}
